name: Build Image
permissions:
  packages: write
on:
  push:
    branches:
      - '**'
    tags:
      - '**'
  pull_request:
env:
  IMAGE_NAME: "sacd-extract"

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3.5.0

      - uses: cachix/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      
      - run: sudo apt-get update; sudo apt-get -y install skopeo

      - run: nix build .#docker
      
      - run: skopeo copy docker-archive:result docker://ghcr.io/jmmaloney4/sacd-extract:latest --dest-creds ghcr.io/${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}
